[workspace]
members = [ "crates/sable-ast", "crates/sable-common","crates/sable-parser", "sablec"]
resolver = "3"

[workspace.dependecies]
getset = "0.1.6"
smallvec = "1.15.1"
typed-builder = "0.21.0"
anyhow = "1.0.98"
