[workspace]
members = [
  "crates/sable-ast",
  "crates/sable-common",
  "crates/sable-parser", "crates/sable-report", 
  "sablec",
]
resolver = "3"

[workspace.dependencies]
getset = "0.1.6"
smallvec = "1.15.1"
typed-builder = "0.21.0"
bumpalo = "3.18.1"
pretty = "0.12.4"
colored = "3.0.0"

sable-ast = { path = "crates/sable-ast" }
sable-common = { path = "crates/sable-common" }
sable-parser = { path = "crates/sable-parser" }
sable-report = { path = "crates/sable-report" }