[package]
name = "sable-ffi"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
sable-common = { workspace = true }
sable-ast = { workspace = true }
sable-parser = { workspace = true }

[build-dependencies]
cbindgen = "0.29.0"
