[package]
name = "sablec"
version = "0.1.0"
edition = "2024"

[dependencies]
sable-parser = { workspace = true }
sable-ast = { workspace = true }
sable-common = { workspace = true }
bumpalo = { workspace = true }
smallvec = { workspace = true }
ariadne = { workspace = true }