[package]
name = "sable-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
sable-ast = { workspace = true }
sable-common = { workspace = true }
getset = { workspace = true }
sable-report = { workspace = true }
smallvec = { workspace = true }
